apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: worker
  name: worker
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template: 
    metadata: 
      labels: 
        app: worker
    spec: 
      containers: 
      - name: worker
        image: "registry.digitalocean.com/voting-app-example/worker:<TAG>"
      imagePullSecrets:
      - name: voting-app-example-do-registry
